### PR TITLE
add 404 route

### PR DESCRIPTION
**Pull request by Ritesh-Dabral**
Screenshot 2023-10-01 at 3 54 46 PM
Screenshot 2023-10-01 at 3 54 24 PM

### CODE REVIEW

**Comment by Ritesh-Dabral** [comment]
@rahulkamilya Confirm the changes and comment if need to change anything. Color code matches the current system, let me know if additional functionalities are required"

**Comment by rahulkamilya** [comment]
Would you like to add that kind of page @Ritesh-Dabral 

image

**Comment by Ritesh-Dabral** [comment]
@rahulkamilya Sure I can do that, but the font and color code don't match with your existing system. Is that okay with you?

**Comment by rahulkamilya** [comment]
oky no problem @Ritesh-Dabral

**Comment by Ritesh-Dabral** [comment]
### mobile
Screenshot 2023-10-01 at 8 52 58 PM

### desktop
Screenshot 2023-10-01 at 8 52 44 PM


@rahulkamilya Kindly verify the changes

**Comment by rahulkamilya** [comment]
Everything is ok, But I found that error ! @Ritesh-Dabral 

image

**Comment by Ritesh-Dabral** [comment]
let me 

> Everything is ok, But I found that error ! @Ritesh-Dabral
> 
> image

Which error ? There is no conflict with the main branch. I haven't made any changes to this search box or the component. You can verify this from the files that I made changes to. 
If it is another issue, please create a ticket and assign it to me.

**Comment by Ritesh-Dabral** [comment]
> Everything is ok, But I found that error ! @Ritesh-Dabral
> 
> image

Kindly check now

**Pull request merged**
